---
sudo: required
language: python
python:
  - "3.6"
services:
  - docker

before_install:
  # Prepare Travis environment
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5

  # Required packages
  - sudo apt install -y sshpass jq

  # Install Ansible
  - pip install -U pip setuptools docker
  - pip install ansible

script:
  - export TEST_HOME=`pwd`
  - ansible --version
  - echo ### prepare environment
  - docker run -d --security-opt label:disable --cap-add SYS_ADMIN --name node-1 -h node-${i} -p 8081:80 irixjp/katacoda:latest /sbin/init
  - docker ps -a
  - docker top node-1
  - docker exec -it node-1  sh -c "systemctl start sshd"
  - cd ${TEST_HOME:?}/master-course-data/assets/tools
#  - echo "localhost ansible_connection=local ansible_python_interpreter=`which python`" > inventory
#  - >
#    ansible-playbook -i inventory -c local kata_prepare.yml
#    -e "inventory_path=${HOME:?}/inventory"
#    -e "keypair_path=${HOME:?}/automation-keypair.pem"
  - echo "### 101"
  - echo "### 102"
  - echo "### 103"

notifications:
  email: false
